info:
  name: _project.artifactId_ Application
  version: _project.version_
  contact: qapterserver@solera.com
server:
  port: 8080
  
endpoint:
  rest:
    cxf:
      rs-endpoint: /rs
      
integration:
  soap:
    cxf:
      clients:
        taskClient_default:
          active: true
          endpoint: https://www-i2ref.audatex.net/b2b/services/TaskService_v1
        taskClient:
          active: true
          endpoint: https://www-i2ref.audatex.net/b2b/services/TaskService_v1
        taskClient_gas_ch_i1ref:
          active: true
          endpoint: https://www-i1ref.audatex.net/b2b/services/TaskService_v1
        taskClient_gas_ch_i2ref:
          active: true
          endpoint: https://www-i2ref.audatex.net/b2b/services/TaskService_v1
        taskClient_gas_de_int1:
          active: true
          endpoint: https://www-int1.audanet.de/b2b/services/TaskService_v1
        taskClient_gas_de_int2:
          active: true
          endpoint: https://www-int2.audanet.de/b2b/services/TaskService_v1
        taskClient_gas_de_ct:
          active: true
          endpoint: https://www-ct.audanet.de/b2b/services/TaskService_v1
        taskClient_gas_de_cae:
          active: true
          endpoint: https://www-a.audanet.de/b2b/services/TaskService_v1
        taskClient_cee_hr_cae:
          active: true
          endpoint: https://www-a.audatex.net/b2b/services/TaskService_v1
        taskClient_cee-hr:
          active: true
          endpoint: https://www.cee.audatex.net/b2b/services/TaskService_v1
        taskClient_apac2_au_int1:
          active: true
          endpoint: https://audanet-int1.audatex.com.au/b2b/services/TaskService_v1

logging:
  level:
    root: info
    org.springframework: info
    
---

spring:
  profiles: proxy
      
generic:
  proxy:
    java:
      http-host: proxy1.audatex.es
      http-port: 80
      https-host: proxy1.audatex.es
      https-port: 80 
